"""ARC-AGI-3 agent: a thin Python shell around a C++ decision core.

The competition scores each completed level as (human_actions / agent_actions)^2,
so a real action is expensive and thinking is free. Everything that constitutes
thinking - object extraction, working out which sprite the keys move, learning
which cells block, planning a route, replaying the move that finished the last
level - happens in C++ (`arc3_core.cpp`). Python only talks to the environment.

This file is generated by `scripts/bundle_agent.py`, which splices the C++
source into CPP_SOURCE below so the whole agent ships as one file, the way the
Kaggle notebook builder expects. The C++ is compiled on first use with the g++
that is already in the Kaggle image; if that fails for any reason we fall back
to a pure-Python port of the same policy so a submission is never lost.
"""
from __future__ import annotations

import ctypes
import hashlib
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

from arcengine import FrameData, GameAction, GameState
from agents.agent import Agent

# ---------------------------------------------------------------------------
# C++ core (spliced in by the bundler; empty during raw template editing).
# ---------------------------------------------------------------------------
CPP_SOURCE = r"""__ARC3_CPP_SOURCE__"""


def _build_core() -> ctypes.CDLL | None:
    """Compile the embedded C++ core and load it. Returns None if unavailable."""
    src = CPP_SOURCE
    # During local development prefer the file on disk so edits take effect.
    dev = os.environ.get("ARC3_CPP")
    if dev and Path(dev).exists():
        src = Path(dev).read_text(encoding="utf-8")
    if not src.strip() or src.startswith("__ARC3_CPP"):
        return None

    tag = hashlib.sha1(src.encode()).hexdigest()[:12]
    outdir = Path(os.environ.get("ARC3_BUILD_DIR", tempfile.gettempdir())) / "arc3"
    outdir.mkdir(parents=True, exist_ok=True)
    ext = ".dll" if sys.platform == "win32" else ".so"
    lib = outdir / f"arc3_core_{tag}{ext}"

    if not lib.exists():
        cpp = outdir / f"arc3_core_{tag}.cpp"
        cpp.write_text(src, encoding="utf-8")
        cmd = ["g++", "-O2", "-std=c++17", "-shared"]
        if sys.platform != "win32":
            cmd.append("-fPIC")
        cmd += [str(cpp), "-o", str(lib)]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            if r.returncode != 0:
                print(f"[arc3] g++ failed, falling back to Python:\n{r.stderr[:800]}",
                      file=sys.stderr)
                return None
        except Exception as e:  # g++ missing, timeout, ...
            print(f"[arc3] cannot build core ({e}); falling back to Python", file=sys.stderr)
            return None

    try:
        dll = ctypes.CDLL(str(lib))
    except OSError as e:
        print(f"[arc3] cannot load core ({e}); falling back to Python", file=sys.stderr)
        return None

    dll.arc3_new.argtypes = [ctypes.POINTER(ctypes.c_int), ctypes.c_int]
    dll.arc3_new.restype = ctypes.c_int
    dll.arc3_free.argtypes = [ctypes.c_int]
    dll.arc3_observe.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int8),
                                 ctypes.c_int, ctypes.c_int]
    dll.arc3_choose.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int),
                                ctypes.POINTER(ctypes.c_int)]
    dll.arc3_choose.restype = ctypes.c_int
    dll.arc3_stats.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
    return dll


_CORE: ctypes.CDLL | None = None
_CORE_TRIED = False


def _core() -> ctypes.CDLL | None:
    global _CORE, _CORE_TRIED
    if not _CORE_TRIED:
        _CORE_TRIED = True
        _CORE = _build_core()
    return _CORE


_ACTION_BY_VALUE = {a.value: a for a in GameAction}

# GameState is a string enum; the C++ side wants a small integer.
_STATE_CODE = {
    GameState.NOT_PLAYED: 0,
    GameState.NOT_FINISHED: 1,
    GameState.WIN: 2,
    GameState.GAME_OVER: 3,
}


class MyAgent(Agent):
    """Explore deliberately, then repeat what worked."""

    # The framework stops us here; the harness overrides it with the real
    # per-game budget (5x the human baseline, summed over levels).
    MAX_ACTIONS = 100_000

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._h = -1
        self._py = None  # pure-Python fallback policy
        self._started = False

    # -- lifecycle ---------------------------------------------------------
    def _start(self, latest_frame: FrameData) -> None:
        acts = list(getattr(latest_frame, "available_actions", None) or [1, 2, 3, 4, 5, 6])
        acts = [int(a) for a in acts]
        core = _core()
        if core is not None:
            arr = (ctypes.c_int * len(acts))(*acts)
            self._h = core.arc3_new(arr, len(acts))
        else:
            from_py = _PyPolicy(acts)
            self._py = from_py
        self._started = True

    def is_done(self, frames: list[FrameData], latest_frame: FrameData) -> bool:
        return latest_frame.state is GameState.WIN

    def choose_action(self, frames: list[FrameData], latest_frame: FrameData) -> GameAction:
        if latest_frame.state in (GameState.NOT_PLAYED, GameState.GAME_OVER):
            return GameAction.RESET

        if not self._started:
            self._start(latest_frame)

        grid = latest_frame.frame[-1] if latest_frame.frame else None
        if grid is None:
            return GameAction.RESET

        flat = bytearray(64 * 64)
        for y, row in enumerate(grid[:64]):
            base = y * 64
            for x, v in enumerate(row[:64]):
                flat[base + x] = v & 0xFF

        core = _core()
        if core is not None and self._h >= 0:
            buf = (ctypes.c_int8 * (64 * 64)).from_buffer(flat)
            core.arc3_observe(self._h, buf, int(latest_frame.levels_completed),
                              _STATE_CODE.get(latest_frame.state, 0))
            cx, cy = ctypes.c_int(0), ctypes.c_int(0)
            val = core.arc3_choose(self._h, ctypes.byref(cx), ctypes.byref(cy))
            x, y = cx.value, cy.value
        else:
            val, x, y = self._py.step(grid, int(latest_frame.levels_completed))

        action = _ACTION_BY_VALUE.get(val, GameAction.ACTION1)
        if action.is_complex():
            action.set_data({"x": int(x) & 63, "y": int(y) & 63})
            action.reasoning = {"src": "arc3_core", "x": int(x), "y": int(y)}
        else:
            action.reasoning = "arc3_core"
        return action

    def cleanup(self, *args: Any, **kwargs: Any) -> None:
        core = _core()
        if core is not None and self._h >= 0:
            core.arc3_free(self._h)
            self._h = -1
        super().cleanup(*args, **kwargs)


class _PyPolicy:
    """Minimal fallback used only when the C++ core cannot be built.

    Deliberately simple: cycle the simple actions, and aim complex actions at
    object centroids rather than random pixels. Still far better than random,
    but the real policy is the C++ one.
    """

    def __init__(self, actions: list[int]) -> None:
        self.simple = [a for a in actions if 1 <= a <= 5]
        self.has6 = 6 in actions
        self.i = 0
        self.clicked: set[tuple[int, int]] = set()

    def step(self, grid, levels_completed: int):
        self.i += 1
        if self.simple and (not self.has6 or self.i % 3):
            return self.simple[self.i % len(self.simple)], 0, 0
        if self.has6:
            for y in range(2, 64, 4):
                for x in range(2, 64, 4):
                    if (x, y) not in self.clicked:
                        self.clicked.add((x, y))
                        return 6, x, y
        return (self.simple[self.i % len(self.simple)] if self.simple else 1), 0, 0
