"""ARC-AGI-3 agent: a thin Python shell around a C++ decision core.

The competition scores each completed level as (human_actions / agent_actions)^2,
so a real action is expensive and thinking is free. Everything that constitutes
thinking - object extraction, working out which sprite the keys move, learning
which cells block, planning a route, replaying the move that finished the last
level - happens in C++ (`arc3_core.cpp`). Python only talks to the environment.

This file is generated by `scripts/bundle_agent.py`, which splices the C++
source into CPP_SOURCE below so the whole agent ships as one file, the way the
Kaggle notebook builder expects. The C++ is compiled on first use with the g++
that is already in the Kaggle image; if that fails for any reason we fall back
to a pure-Python port of the same policy so a submission is never lost.
"""
from __future__ import annotations

import ctypes
import hashlib
import os
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

from arcengine import FrameData, GameAction, GameState
from agents.agent import Agent

# ---------------------------------------------------------------------------
# C++ core (spliced in by the bundler; empty during raw template editing).
# ---------------------------------------------------------------------------
CPP_SOURCE = r"""__ARC3_CPP_SOURCE__"""


def _build_core() -> ctypes.CDLL | None:
    """Compile the embedded C++ core and load it. Returns None if unavailable."""
    src = CPP_SOURCE
    # During local development prefer the file on disk so edits take effect.
    dev = os.environ.get("ARC3_CPP")
    if dev and Path(dev).exists():
        src = Path(dev).read_text(encoding="utf-8")
    if not src.strip() or src.startswith("__ARC3_CPP"):
        return None

    tag = hashlib.sha1(src.encode()).hexdigest()[:12]
    outdir = Path(os.environ.get("ARC3_BUILD_DIR", tempfile.gettempdir())) / "arc3"
    outdir.mkdir(parents=True, exist_ok=True)
    ext = ".dll" if sys.platform == "win32" else ".so"
    lib = outdir / f"arc3_core_{tag}{ext}"

    if not lib.exists():
        # Build to a private name and rename into place: several evaluation
        # processes run in parallel and must not half-read each other's output.
        cpp = outdir / f"arc3_core_{tag}_{os.getpid()}.cpp"
        cpp.write_text(src, encoding="utf-8")
        tmp = outdir / f"arc3_core_{tag}_{os.getpid()}.building{ext}"
        # -pthread: the autograd engine parallelises convolutions over the
        # batch with std::thread, and on Linux that needs the flag at both
        # compile and link time or the threads fail at runtime.
        cmd = ["g++", "-O2", "-std=c++17", "-shared", "-pthread"]
        if sys.platform != "win32":
            cmd.append("-fPIC")
        cmd += [str(cpp), "-o", str(tmp)]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            if r.returncode != 0:
                print(f"[arc3] g++ failed, falling back to Python:\n{r.stderr[:800]}",
                      file=sys.stderr)
                return None
            try:
                os.replace(tmp, lib)
            except OSError:
                # Someone else won the race; their build is byte-identical.
                pass
        except Exception as e:  # g++ missing, timeout, ...
            print(f"[arc3] cannot build core ({e}); falling back to Python", file=sys.stderr)
            return None
        finally:
            for f in (cpp, tmp):
                try:
                    f.unlink()
                except OSError:
                    pass

    # Windows keeps a loaded DLL locked, which would block the next build, so
    # every process loads its own copy.
    private = outdir / f"arc3_core_{tag}_p{os.getpid()}{ext}"
    try:
        if not private.exists():
            private.write_bytes(lib.read_bytes())
        dll = ctypes.CDLL(str(private))
    except OSError as e:
        print(f"[arc3] cannot load core ({e}); falling back to Python", file=sys.stderr)
        return None

    dll.arc3_new.argtypes = [ctypes.POINTER(ctypes.c_int), ctypes.c_int]
    dll.arc3_new.restype = ctypes.c_int
    dll.arc3_free.argtypes = [ctypes.c_int]
    dll.arc3_observe.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int8),
                                 ctypes.c_int, ctypes.c_int]
    dll.arc3_choose.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int),
                                ctypes.POINTER(ctypes.c_int)]
    dll.arc3_choose.restype = ctypes.c_int
    dll.arc3_stats.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
    dll.arc3_set_explore.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_alphabet.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.c_int]
    dll.arc3_set_depth.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_forget.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_trigger.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_clear_stats.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_budget.argtypes = [ctypes.c_int, ctypes.c_int]
    return dll


_CORE: ctypes.CDLL | None = None
_CORE_TRIED = False


def _core() -> ctypes.CDLL | None:
    global _CORE, _CORE_TRIED
    if not _CORE_TRIED:
        _CORE_TRIED = True
        _CORE = _build_core()
    return _CORE


_ACTION_BY_VALUE = {a.value: a for a in GameAction}

# GameState is a string enum; the C++ side wants a small integer.
_STATE_CODE = {
    GameState.NOT_PLAYED: 0,
    GameState.NOT_FINISHED: 1,
    GameState.WIN: 2,
    GameState.GAME_OVER: 3,
}


# The framework plays every game at once - Swarm starts one thread per game
# (agents/swarm.py) - so games do not share the clock, they each get the whole
# run. Capping a game at five minutes was therefore pure self-harm: the official
# sample plays each game for eight hours and scores about 3.5, while this agent
# stopped after 300 seconds and scored 0.19.
_PROCESS_START = time.monotonic()
_GAME_BUDGET_S = 8 * 3600 - 5 * 60   # what the sample uses, inside the 12 h limit


class MyAgent(Agent):
    """Explore deliberately, then repeat what worked."""

    # Not a real limit: the framework stops on is_done, and stopping early only
    # forfeits levels. The harness overrides it when measuring locally.
    MAX_ACTIONS = 10_000_000

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._h = -1
        self._py = None  # pure-Python fallback policy
        self._started = False
        self._t0 = time.monotonic()

    # -- lifecycle ---------------------------------------------------------
    def _start(self, latest_frame: FrameData) -> None:
        acts = list(getattr(latest_frame, "available_actions", None) or [1, 2, 3, 4, 5, 6])
        acts = [int(a) for a in acts]
        core = _core()
        if core is not None:
            arr = (ctypes.c_int * len(acts))(*acts)
            self._h = core.arc3_new(arr, len(acts))
            # 8 = count, per action and per coordinate, how often it changed the
            # frame, and sample by the posterior mean. It is the official
            # sample's idea without the network, and on the 25 public games it
            # completes 8 levels against 3-4 for every other mode here.
            core.arc3_set_explore(self._h, int(os.environ.get("ARC3_EXPLORE", "8")))
            # ARC3_ALPHA_GRID=0: offer only object centroids as click targets.
            # The coarse sweep was 256 candidates against ~48 objects, diluting
            # the search five to one, and every click that ended a level in the
            # offline solutions landed on an object. Measured on all 25 games:
            # no sweep 16 levels / 0.38, sparse 9 / 0.36, dense 8 / 0.02.
            core.arc3_set_alphabet(self._h,
                                   int(os.environ.get("ARC3_ALPHA_OBJ", "24")),
                                   int(os.environ.get("ARC3_ALPHA_GRID", "0")))
            core.arc3_set_depth(self._h, int(os.environ.get("ARC3_DEPTH", "12")))
            core.arc3_set_forget(self._h, int(os.environ.get("ARC3_FORGET", "0")))
            core.arc3_set_trigger(self._h, int(os.environ.get("ARC3_TRIGGER", "0")))
            core.arc3_set_clear_stats(self._h, int(os.environ.get("ARC3_CLEAR", "1")))
            core.arc3_set_budget(self._h, int(self.MAX_ACTIONS))
        else:
            from_py = _PyPolicy(acts)
            self._py = from_py
        self._started = True

    def is_done(self, frames: list[FrameData], latest_frame: FrameData) -> bool:
        if latest_frame.state is GameState.WIN:
            return True
        # Keep playing until the run is nearly over. There is nothing to save
        # the time for - the other games are already running in their own
        # threads - and a level left unfinished scores zero however few actions
        # were spent failing to finish it.
        return time.monotonic() - _PROCESS_START > _GAME_BUDGET_S

    def choose_action(self, frames: list[FrameData], latest_frame: FrameData) -> GameAction:
        if latest_frame.state is GameState.NOT_PLAYED:
            return GameAction.RESET

        if not self._started:
            self._start(latest_frame)

        # GAME_OVER is not short-circuited here on purpose. RESET restarts the
        # current level and keeps the levels already finished, so it is a move
        # in the search rather than an admission of defeat - and the core is
        # what decides where to resume from. It is told the state and returns
        # RESET itself when that is the only legal action.
        grid = latest_frame.frame[-1] if latest_frame.frame else None
        if grid is None:
            return GameAction.RESET

        flat = bytearray(64 * 64)
        for y, row in enumerate(grid[:64]):
            base = y * 64
            for x, v in enumerate(row[:64]):
                flat[base + x] = v & 0xFF

        core = _core()
        if core is not None and self._h >= 0:
            buf = (ctypes.c_int8 * (64 * 64)).from_buffer(flat)
            core.arc3_observe(self._h, buf, int(latest_frame.levels_completed),
                              _STATE_CODE.get(latest_frame.state, 0))
            cx, cy = ctypes.c_int(0), ctypes.c_int(0)
            val = core.arc3_choose(self._h, ctypes.byref(cx), ctypes.byref(cy))
            x, y = cx.value, cy.value
        else:
            val, x, y = self._py.step(grid, int(latest_frame.levels_completed))

        action = _ACTION_BY_VALUE.get(val, GameAction.ACTION1)
        if action.is_complex():
            action.set_data({"x": int(x) & 63, "y": int(y) & 63})
            action.reasoning = {"src": "arc3_core", "x": int(x), "y": int(y)}
        else:
            action.reasoning = "arc3_core"
        return action

    # Filled in on cleanup so an evaluation run can report what the core
    # actually worked out about each game, not just the score.
    STAT_NAMES = ("avatar_known", "avatar_color", "ax", "ay", "steps", "levels",
                  "trigger", "blocked", "av_w", "av_h", "plan", "stagnant",
                  "touched", "escalation", "states", "restarts",
                  "rules", "goals", "walls", "wm_obs", "wm_classes", "scenes",
                  "objects", "bfs_queue", "probes", "alphabet", "solution_len",
                  "pruned", "bfs_head", "routes", "expanded")

    def cleanup(self, *args: Any, **kwargs: Any) -> None:
        core = _core()
        if core is not None and self._h >= 0:
            buf = (ctypes.c_int * 32)()
            core.arc3_stats(self._h, buf)
            self.final_stats = dict(zip(self.STAT_NAMES, list(buf)))
            core.arc3_free(self._h)
            self._h = -1
        super().cleanup(*args, **kwargs)


class _PyPolicy:
    """Minimal fallback used only when the C++ core cannot be built.

    Deliberately simple: cycle the simple actions, and aim complex actions at
    object centroids rather than random pixels. Still far better than random,
    but the real policy is the C++ one.
    """

    def __init__(self, actions: list[int]) -> None:
        self.simple = [a for a in actions if 1 <= a <= 5]
        self.has6 = 6 in actions
        self.i = 0
        self.clicked: set[tuple[int, int]] = set()

    def step(self, grid, levels_completed: int):
        self.i += 1
        if self.simple and (not self.has6 or self.i % 3):
            return self.simple[self.i % len(self.simple)], 0, 0
        if self.has6:
            for y in range(2, 64, 4):
                for x in range(2, 64, 4):
                    if (x, y) not in self.clicked:
                        self.clicked.add((x, y))
                        return 6, x, y
        return (self.simple[self.i % len(self.simple)] if self.simple else 1), 0, 0
