"""ARC-AGI-3 agent: a thin Python shell around a C++ decision core.

The competition scores each completed level as (human_actions / agent_actions)^2,
so a real action is expensive and thinking is free. Everything that constitutes
thinking - object extraction, working out which sprite the keys move, learning
which cells block, planning a route, replaying the move that finished the last
level - happens in C++ (`arc3_core.cpp`). Python only talks to the environment.

This file is generated by `scripts/bundle_agent.py`, which splices the C++
source into CPP_SOURCE below so the whole agent ships as one file, the way the
Kaggle notebook builder expects. The C++ is compiled on first use with the g++
that is already in the Kaggle image; if that fails for any reason we fall back
to a pure-Python port of the same policy so a submission is never lost.
"""
from __future__ import annotations

import ctypes
import hashlib
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

from arcengine import FrameData, GameAction, GameState
from agents.agent import Agent

# ---------------------------------------------------------------------------
# C++ core (spliced in by the bundler; empty during raw template editing).
# ---------------------------------------------------------------------------
CPP_SOURCE = r"""__ARC3_CPP_SOURCE__"""


def _build_core() -> ctypes.CDLL | None:
    """Compile the embedded C++ core and load it. Returns None if unavailable."""
    src = CPP_SOURCE
    # During local development prefer the file on disk so edits take effect.
    dev = os.environ.get("ARC3_CPP")
    if dev and Path(dev).exists():
        src = Path(dev).read_text(encoding="utf-8")
    if not src.strip() or src.startswith("__ARC3_CPP"):
        return None

    # If a Lua source tree is attached, build the scripted layer in as well.
    #
    # The competition notebook has no internet, so the interpreter cannot be
    # installed - but it can be compiled, because it is C and it is small, and
    # one extra translation unit is all it costs. Without it the agent is
    # exactly what it was before: the tabular policy and nothing else.
    lua_src = _find_lua()
    tag = hashlib.sha1((src + (lua_src or "")).encode()).hexdigest()[:12]
    outdir = Path(os.environ.get("ARC3_BUILD_DIR", tempfile.gettempdir())) / "arc3"
    outdir.mkdir(parents=True, exist_ok=True)
    ext = ".dll" if sys.platform == "win32" else ".so"
    lib = outdir / f"arc3_core_{tag}{ext}"

    if not lib.exists():
        # Build to a private name and rename into place: several evaluation
        # processes run in parallel and must not half-read each other's output.
        cpp = outdir / f"arc3_core_{tag}_{os.getpid()}.cpp"
        cpp.write_text(src, encoding="utf-8")
        tmp = outdir / f"arc3_core_{tag}_{os.getpid()}.building{ext}"
        # -pthread: the autograd engine parallelises convolutions over the
        # batch with std::thread, and on Linux that needs the flag at both
        # compile and link time or the threads fail at runtime.
        cmd = ["g++", "-O2", "-std=c++17", "-shared", "-pthread", "-w"]
        if sys.platform != "win32":
            cmd.append("-fPIC")
        cmd += [str(cpp)]
        if lua_src:
            one = outdir / f"lua_one_{tag}_{os.getpid()}.cpp"
            one.write_text(_LUA_ONE, encoding="utf-8")
            cmd += ["-DARC3_WITH_LUA", "-I", lua_src, str(one)]
        cmd += ["-o", str(tmp)]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
            if r.returncode != 0:
                print(f"[arc3] g++ failed, falling back to Python:\n{r.stderr[:800]}",
                      file=sys.stderr)
                return None
            try:
                os.replace(tmp, lib)
            except OSError:
                # Someone else won the race; their build is byte-identical.
                pass
        except Exception as e:  # g++ missing, timeout, ...
            print(f"[arc3] cannot build core ({e}); falling back to Python", flush=True)
            return None
        finally:
            for f in (cpp, tmp):
                try:
                    f.unlink()
                except OSError:
                    pass

    # Windows keeps a loaded DLL locked, which would block the next build, so
    # every process loads its own copy.
    private = outdir / f"arc3_core_{tag}_p{os.getpid()}{ext}"
    try:
        if not private.exists():
            private.write_bytes(lib.read_bytes())
        dll = ctypes.CDLL(str(private))
    except OSError as e:
        print(f"[arc3] cannot load core ({e}); falling back to Python", flush=True)
        return None

    dll.arc3_new.argtypes = [ctypes.POINTER(ctypes.c_int), ctypes.c_int]
    dll.arc3_new.restype = ctypes.c_int
    dll.arc3_free.argtypes = [ctypes.c_int]
    dll.arc3_observe.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int8),
                                 ctypes.c_int, ctypes.c_int]
    dll.arc3_choose.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int),
                                ctypes.POINTER(ctypes.c_int)]
    dll.arc3_choose.restype = ctypes.c_int
    dll.arc3_stats.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
    if hasattr(dll, "arc3_lua_new"):
        dll.arc3_lua_new.argtypes = [ctypes.POINTER(ctypes.c_int), ctypes.c_int]
        dll.arc3_lua_new.restype = ctypes.c_int
        dll.arc3_lua_load.argtypes = [ctypes.c_int, ctypes.c_char_p]
        dll.arc3_lua_load.restype = ctypes.c_int
        dll.arc3_lua_observe.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int8),
                                         ctypes.c_int, ctypes.c_int]
        dll.arc3_lua_step.argtypes = [ctypes.c_int] + [ctypes.POINTER(ctypes.c_int)] * 3
        dll.arc3_lua_step.restype = ctypes.c_int
        dll.arc3_lua_state.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int]
        dll.arc3_lua_state.restype = ctypes.c_int
        dll.arc3_lua_drain.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int]
        dll.arc3_lua_drain.restype = ctypes.c_int
    dll.arc3_set_explore.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_alphabet.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.c_int]
    dll.arc3_set_depth.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_replay.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_handover.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_forget.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_trigger.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_clear_stats.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_balance.argtypes = [ctypes.c_int, ctypes.c_int]
    dll.arc3_set_budget.argtypes = [ctypes.c_int, ctypes.c_int]
    return dll


_CORE: ctypes.CDLL | None = None
_CORE_TRIED = False


# Lua, as one translation unit. The list of .c files is spelled out because
# Lua 5.4 does not ship an amalgamation, and the whole thing is wrapped in
# extern "C" so a C++ build still produces the symbols the API declares.
_LUA_ONE = r"""// Lua as one C++ translation unit.
//
// Our Kaggle notebook compiles a single embedded C++ string with g++ and loads
// the result through ctypes; there is no build system and no second file. So
// the question that matters is not "does Lua build" - it does, everywhere - but
// "does the whole interpreter go into one .cpp with the C++ compiler we already
// have there". That is what this file tests. Lua 5.4 does not ship onelua.c, so
// the includes are listed by hand.
extern "C" {
#include "lprefix.h"
}
// C linkage for the whole interpreter. Compiling Lua as C++ mangles every
// symbol, so a translation unit that declares the API the normal way -
// extern "C", as lua.hpp does - fails to link against it. Wrapping the
// includes fixes that and keeps Lua linkable from C as well.
extern "C" {
#define LUA_CORE
#define LUA_LIB
#define ltable_c
#define lvm_c
#include "lapi.c"
#include "lcode.c"
#include "lctype.c"
#include "ldebug.c"
#include "ldo.c"
#include "ldump.c"
#include "lfunc.c"
#include "lgc.c"
#include "llex.c"
#include "lmem.c"
#include "lobject.c"
#include "lopcodes.c"
#include "lparser.c"
#include "lstate.c"
#include "lstring.c"
#include "ltable.c"
#include "ltm.c"
#include "lundump.c"
#include "lvm.c"
#include "lzio.c"
#include "lauxlib.c"
#include "lbaselib.c"
#include "lcorolib.c"
#include "ldblib.c"
// io/os/loadlib are compiled in because linit.c refers to their luaopen_*.
// Keeping them out of the sandbox is a runtime decision - clear the globals
// after opening - not a compile-time one.
#include "liolib.c"
#include "loslib.c"
#include "loadlib.c"
#include "lmathlib.c"
#include "lstrlib.c"
#include "ltablib.c"
#include "lutf8lib.c"
#include "linit.c"
}
"""


def _find_lua() -> str | None:
    """The directory holding lua.h, if a Lua source tree is attached."""
    import glob
    for pat in ("/kaggle/input/**/lua-*/src/lua.h", "/kaggle/input/**/src/lua.h"):
        hit = glob.glob(pat, recursive=True)
        if hit:
            return str(Path(hit[0]).parent)
    env = os.environ.get("LUA_SRC")
    if env and (Path(env) / "lua.h").exists():
        return env
    return None


# ── the model, when one is attached ──────────────────────────────────────────
#
# Measured on Kaggle's two T4s with Qwen3.8-27B Q4_K_M: the weights load in
# 1m52s, the prompt runs at 65 tokens a second and the answer at 13, so one
# question costs about a minute. Eight hours buys roughly 480 of them across
# all twenty-five games - about nineteen each. That is far fewer than the
# leading harness gets, so each one has to buy a lot of actions: the model
# writes a script, and the script plays.

_LLM = {"url": None, "proc": None, "tried": False}


def _llm_url() -> str | None:
    """Start llama-server once, if its binaries and a model are attached."""
    if _LLM["tried"]:
        return _LLM["url"]
    _LLM["tried"] = True
    import glob, shutil, stat, urllib.request

    env_url = os.environ.get("LLAMA_SERVER")
    if env_url:
        _LLM["url"] = env_url
        return env_url

    # vLLM first, when the image has it and a model directory is attached.
    #
    # Both serve the same OpenAI-compatible endpoint, so nothing above this
    # function changes. vLLM is the better one where it exists: it batches
    # continuously and, on a Qwen that supports it, decodes several tokens per
    # step. llama.cpp is what makes the agent work at all on the ordinary Kaggle
    # image, which has no vLLM and no way to install one.
    import importlib.util
    if importlib.util.find_spec("vllm") is not None:
        cfgs = glob.glob("/kaggle/input/**/config.json", recursive=True)
        if cfgs:
            model_dir = str(Path(sorted(cfgs, key=len)[0]).parent)
            print("[llm] vllm serving " + model_dir, flush=True)
            cmd = [sys.executable, "-m", "vllm.entrypoints.openai.api_server",
                   "--model", model_dir, "--host", "127.0.0.1", "--port", "8080",
                   "--max-model-len", os.environ.get("VLLM_MAXLEN", "16384"),
                   "--gpu-memory-utilization", os.environ.get("VLLM_UTIL", "0.90")]
            log = open(str(Path(tempfile.gettempdir()) / "vllm.log"), "w")
            try:
                _LLM["proc"] = subprocess.Popen(cmd, stdout=log,
                                                stderr=subprocess.STDOUT)
                return _wait_for_server()
            except Exception as e:
                print("[llm] cannot start vllm: %s" % e, flush=True)


    exe = glob.glob("/kaggle/input/**/llama-server", recursive=True)
    gguf = sorted(glob.glob("/kaggle/input/**/*.gguf", recursive=True),
                  key=os.path.getsize, reverse=True)
    if not exe or not gguf:
        print("[llm] no server or model attached; the tabular policy plays alone",
              file=sys.stderr)
        return None

    run = Path(tempfile.gettempdir()) / "llamabin"
    run.mkdir(exist_ok=True)
    for f in Path(exe[0]).parent.iterdir():
        if f.suffix != ".json":
            shutil.copy2(f, run / f.name)
    server = run / "llama-server"
    server.chmod(server.stat().st_mode | stat.S_IEXEC)

    env = dict(os.environ,
               LD_LIBRARY_PATH=str(run) + ":" + os.environ.get("LD_LIBRARY_PATH", ""))
    cmd = [str(server), "-m", gguf[0], "-ngl", "99", "--tensor-split", "1,1",
           "-c", "24576", "-np", "4", "--host", "127.0.0.1", "--port", "8080",
           "--jinja"]
    log = open(str(Path(tempfile.gettempdir()) / "llama-server.log"), "w")
    try:
        _LLM["proc"] = subprocess.Popen(cmd, stdout=log, stderr=subprocess.STDOUT,
                                        env=env, cwd=str(run))
    except Exception as e:
        print(f"[llm] cannot start server: {e}", flush=True)
        return None

    return _wait_for_server()


def _wait_for_server(limit: int = 360) -> str | None:
    """Wait for whichever server was started. vLLM takes the longer end of it."""
    import urllib.request
    for _ in range(limit):
        time.sleep(5)
        if _LLM["proc"] is not None and _LLM["proc"].poll() is not None:
            print("[llm] server exited rc=%s" % _LLM["proc"].returncode, flush=True)
            return None
        for path in ("/health", "/v1/models"):
            try:
                with urllib.request.urlopen("http://127.0.0.1:8080" + path,
                                            timeout=3) as r:
                    r.read()
                _LLM["url"] = "http://127.0.0.1:8080"
                print("[llm] server up", flush=True)
                return _LLM["url"]
            except Exception:
                pass
    print("[llm] server never came up", flush=True)
    return None

def _ask(prompt: str, n_predict: int = 500) -> str | None:
    """One question. Returns None on any failure, and says so - a slow or
    broken path that hides itself is worse than no path at all."""
    url = _llm_url()
    if not url:
        return None
    import json as _json, urllib.request
    body = _json.dumps({
        "messages": [
            {"role": "system",
             "content": "You write Lua. Reply with Lua source only: no markdown "
                        "fence, no explanation."},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": n_predict, "temperature": 0.2,
        "chat_template_kwargs": {"enable_thinking": False},
    }).encode("utf-8")
    req = urllib.request.Request(url + "/v1/chat/completions", data=body,
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=600) as r:
            return _json.load(r)["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"[llm] call failed: {str(e)[:200]}", flush=True)
        return None


_LUA_START = re.compile(r"^\s*(--|local|for|while|if|function|repeat"
                        r"|do|return|[A-Za-z_][A-Za-z_0-9]*\s*[=(])")


def _only_lua(text: str) -> str:
    """Take the program out of the answer.

    Guessing where the code starts does not work. The model writes a sentence,
    then the program, and the first line that looks like Lua is often the middle
    of it - cut there and a function's opening is gone while its `end` remains,
    which Lua reports as "<eof> expected near 'end'" and the turn is wasted.
    Both of the first two attempts failed exactly that way.
    So the prompt asks for a fence and this takes what is inside it. The old
    guess stays as a fallback for an answer that arrives without one.
    """
    fence = "`" * 3
    m = re.search(fence + r"(?:lua)?[ 	]*" + chr(92) + "n(.*?)" + fence, text, re.S)
    if m:
        return m.group(1).strip()
    lines = [l for l in text.splitlines() if l.strip()]
    while lines and not _LUA_START.match(lines[0]):
        lines.pop(0)
    return chr(10).join(lines).strip()


def _core() -> ctypes.CDLL | None:
    global _CORE, _CORE_TRIED
    if not _CORE_TRIED:
        _CORE_TRIED = True
        _CORE = _build_core()
    return _CORE


_ACTION_BY_VALUE = {a.value: a for a in GameAction}

# GameState is a string enum; the C++ side wants a small integer.
_STATE_CODE = {
    GameState.NOT_PLAYED: 0,
    GameState.NOT_FINISHED: 1,
    GameState.WIN: 2,
    GameState.GAME_OVER: 3,
}


# The framework plays every game at once - Swarm starts one thread per game
# (agents/swarm.py) - so games do not share the clock, they each get the whole
# run. Capping a game at five minutes was therefore pure self-harm: the official
# sample plays each game for eight hours and scores about 3.5, while this agent
# stopped after 300 seconds and scored 0.19.
_PROCESS_START = time.monotonic()
_GAME_BUDGET_S = 8 * 3600 - 5 * 60   # what the sample uses, inside the 12 h limit


class MyAgent(Agent):
    """Explore deliberately, then repeat what worked."""

    # Not a real limit: the framework stops on is_done, and stopping early only
    # forfeits levels. The harness overrides it when measuring locally.
    MAX_ACTIONS = 10_000_000

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._h = -1
        self._py = None  # pure-Python fallback policy
        self._started = False
        self._t0 = time.monotonic()

    # -- lifecycle ---------------------------------------------------------
    _lua = -1
    _script_live = False
    _story = ""
    _asks = int(os.environ.get("ARC3_ASKS", "20"))
    _pending = (0, 0)
    _since_level = 0
    _last_level = -1
    _patience = int(os.environ.get("ARC3_PATIENCE", "400"))

    def _start(self, latest_frame: FrameData) -> None:
        acts = list(getattr(latest_frame, "available_actions", None) or [1, 2, 3, 4, 5, 6])
        acts = [int(a) for a in acts]
        core = _core()
        if core is not None:
            arr = (ctypes.c_int * len(acts))(*acts)
            self._h = core.arc3_new(arr, len(acts))
            # 8 = count, per action and per coordinate, how often it changed the
            # frame, and sample by the posterior mean. It is the official
            # sample's idea without the network, and on the 25 public games it
            # completes 8 levels against 3-4 for every other mode here.
            core.arc3_set_explore(self._h, int(os.environ.get("ARC3_EXPLORE", "8")))
            # ARC3_ALPHA_GRID=0: offer only object centroids as click targets.
            # The coarse sweep was 256 candidates against ~48 objects, diluting
            # the search five to one, and every click that ended a level in the
            # offline solutions landed on an object. Measured on all 25 games:
            # no sweep 16 levels / 0.38, sparse 9 / 0.36, dense 8 / 0.02.
            core.arc3_set_alphabet(self._h,
                                   int(os.environ.get("ARC3_ALPHA_OBJ", "24")),
                                   int(os.environ.get("ARC3_ALPHA_GRID", "0")))
            core.arc3_set_depth(self._h, int(os.environ.get("ARC3_DEPTH", "12")))
            core.arc3_set_replay(self._h, int(os.environ.get("ARC3_REPLAY", "0")))
            core.arc3_set_handover(self._h, int(os.environ.get("ARC3_HANDOVER", "60")))
            core.arc3_set_forget(self._h, int(os.environ.get("ARC3_FORGET", "0")))
            core.arc3_set_trigger(self._h, int(os.environ.get("ARC3_TRIGGER", "0")))
            core.arc3_set_clear_stats(self._h, int(os.environ.get("ARC3_CLEAR", "1")))
            core.arc3_set_balance(self._h, int(os.environ.get("ARC3_BALANCE", "0")))
            core.arc3_set_budget(self._h, int(self.MAX_ACTIONS))

            # A scripted agent beside the tabular one, if the build has Lua in
            # it. The two share nothing: the script decides while it has one,
            # and the counters play whenever it does not.
            if hasattr(core, "arc3_lua_new") and os.environ.get("ARC3_LLM", "1") != "0":
                try:
                    self._lua = core.arc3_lua_new(arr, len(acts))
                except Exception as e:
                    print(f"[llm] no lua host: {e}", flush=True)
        else:
            from_py = _PyPolicy(acts)
            self._py = from_py
        self._started = True

    # ── the scripted half ────────────────────────────────────────────────────

    _ASK = """You are playing one level of a grid puzzle game by writing short Lua scripts.
I run what you write, then show you what happened and you write the next one.
The game does not restart between your scripts.

These functions exist and nothing else does. There is no io, no os, no require.

  objects()      -> array of objects: x, y, colour, glyph, area, w, h
  changes()      -> what the LAST action did: kind = "moved" (dx, dy, fx, fy),
                    "appeared" or "vanished", each with colour, area, x, y
  at(x, y)       -> colour of that cell, or nil off the board
  size()         -> width, height in cells
  level()        -> levels finished     steps() -> actions used
  actions()      -> the buttons this game offers
  me()           -> the object you control, or nil until something has moved
  walls()        -> cells found impassable
  say(text)      -> a line I will show you afterwards
  press(n)       -> press button n (1..5); true if the board changed
  click(x, y)    -> click that cell; true if the board changed
  move_to(x, y)  -> walk there by the shortest known route. One action per step
                    and the cheapest way to travel; do not write your own loop
  explore(n)     -> hand n actions to a search that is good at finding what
                    changes a board when you have no hypothesis yet
  replay()       -> do again whatever finished the previous level
  restart()      -> restart this level

Coordinates are cells counted from 0. objects() is the truth about positions.

Your score for a level is (the actions a human needed / the actions you spend),
squared, and a game is capped by how many of its levels you finish - so getting
to level two and three matters far more than polishing level one.

I can only ask you about twenty times in this whole game, so a script that
spends five actions and hands back wastes a turn. Write one that keeps going:
loop, test an idea, and if it fails try the next within the same script.

"""

    def _with_data(self, val, x, y):
        act = _ACTION_BY_VALUE.get(val, GameAction.ACTION1)
        if val == 6:
            try:
                act.set_data({"x": int(x), "y": int(y)})
            except Exception:
                pass
        return act

    def _lua_move(self, core, flat, latest_frame):
        """One action from the script, or None to let the counters play."""
        buf = (ctypes.c_int8 * (64 * 64)).from_buffer(flat)
        core.arc3_lua_observe(self._lua, buf, int(latest_frame.levels_completed),
                              _STATE_CODE.get(latest_frame.state, 0))

        if self._script_live:
            a, x, y = ctypes.c_int(0), ctypes.c_int(0), ctypes.c_int(0)
            rc = core.arc3_lua_step(self._lua, ctypes.byref(a), ctypes.byref(x),
                                    ctypes.byref(y))
            if rc == 1:
                self._pending = (x.value, y.value)
                return self._with_data(a.value, x.value, y.value)
            self._script_live = False
            note = self._drain(core)
            if note:
                self._story = (self._story + chr(10) + note)[-2000:]

        if self._asks <= 0:
            return None
        self._asks -= 1
        brief = self._brief(core)
        text = _ask(self._ASK + "What the board looks like now:" + chr(10) + brief
                    + self._story + chr(10)
                    + "Write the next few moves as Lua. Put the whole program "
                      "between ```lua and ```, and nothing else. Under forty lines.")
        if not text:
            print("[llm] no answer", flush=True)
            return None
        script = _only_lua(text)
        if not script:
            print("[llm] answer had no lua: %r" % text[:160], flush=True)
            return None
        print("[llm] got %d lines of lua" % len(script.splitlines()), flush=True)
        if core.arc3_lua_load(self._lua, script.encode("utf-8")) != 0:
            err = self._drain(core)[:300]
            print("[llm] did not compile: %s" % err.replace(chr(10), " "), flush=True)
            self._story = (self._story + chr(10) + "that did not compile: " + err)[-2000:]
            return None
        self._script_live = True
        return self._lua_move(core, flat, latest_frame)

    def _brief(self, core) -> str:
        b = ctypes.create_string_buffer(16384)
        n = core.arc3_lua_state(self._lua, b, len(b))
        return b.value.decode("utf-8", "replace") if n else ""

    def _drain(self, core) -> str:
        b = ctypes.create_string_buffer(8192)
        n = core.arc3_lua_drain(self._lua, b, len(b))
        return b.value.decode("utf-8", "replace") if n else ""

    def is_done(self, frames: list[FrameData], latest_frame: FrameData) -> bool:
        if latest_frame.state is GameState.WIN:
            return True
        # Keep playing until the run is nearly over. There is nothing to save
        # the time for - the other games are already running in their own
        # threads - and a level left unfinished scores zero however few actions
        # were spent failing to finish it.
        return time.monotonic() - _PROCESS_START > _GAME_BUDGET_S

    def choose_action(self, frames: list[FrameData], latest_frame: FrameData) -> GameAction:
        if latest_frame.state is GameState.NOT_PLAYED:
            return GameAction.RESET

        if not self._started:
            self._start(latest_frame)

        # GAME_OVER is not short-circuited here on purpose. RESET restarts the
        # current level and keeps the levels already finished, so it is a move
        # in the search rather than an admission of defeat - and the core is
        # what decides where to resume from. It is told the state and returns
        # RESET itself when that is the only legal action.
        grid = latest_frame.frame[-1] if latest_frame.frame else None
        if grid is None:
            return GameAction.RESET

        flat = bytearray(64 * 64)
        for y, row in enumerate(grid[:64]):
            base = y * 64
            for x, v in enumerate(row[:64]):
                flat[base + x] = v & 0xFF

        core = _core()
        # Only call on the model where the counters are stuck.
        #
        # Measured on tn36: the tabular policy finishes level one at human cost,
        # which is exactly the cap for finishing one level of a seven-level
        # game - 3.57 - so there is nothing above it to win. Letting the model
        # spend actions there took the same level more slowly and scored 2.53.
        # Where the counters already win fast, the model is pure cost; where
        # they never win at all - thirteen of the twenty-five games, even at
        # twenty thousand actions - it is the only thing that can help. So it
        # waits until nothing has been finished for a while.
        self._since_level += 1
        if int(latest_frame.levels_completed) > self._last_level:
            self._last_level = int(latest_frame.levels_completed)
            self._since_level = 0
        stuck = self._since_level >= self._patience

        if core is not None and getattr(self, "_lua", -1) >= 0 and (stuck or self._script_live):
            act = self._lua_move(core, flat, latest_frame)
            if act is not None:
                return act

        if core is not None and self._h >= 0:
            buf = (ctypes.c_int8 * (64 * 64)).from_buffer(flat)
            core.arc3_observe(self._h, buf, int(latest_frame.levels_completed),
                              _STATE_CODE.get(latest_frame.state, 0))
            cx, cy = ctypes.c_int(0), ctypes.c_int(0)
            val = core.arc3_choose(self._h, ctypes.byref(cx), ctypes.byref(cy))
            x, y = cx.value, cy.value
        else:
            val, x, y = self._py.step(grid, int(latest_frame.levels_completed))

        action = _ACTION_BY_VALUE.get(val, GameAction.ACTION1)
        if action.is_complex():
            action.set_data({"x": int(x) & 63, "y": int(y) & 63})
            action.reasoning = {"src": "arc3_core", "x": int(x), "y": int(y)}
        else:
            action.reasoning = "arc3_core"
        return action

    # Filled in on cleanup so an evaluation run can report what the core
    # actually worked out about each game, not just the score.
    STAT_NAMES = ("avatar_known", "avatar_color", "ax", "ay", "steps", "levels",
                  "trigger", "blocked", "av_w", "av_h", "plan", "stagnant",
                  "touched", "escalation", "states", "restarts",
                  "rules", "goals", "walls", "wm_obs", "wm_classes", "scenes",
                  "objects", "bfs_queue", "probes", "alphabet", "solution_len",
                  "pruned", "bfs_head", "routes", "expanded")

    def cleanup(self, *args: Any, **kwargs: Any) -> None:
        core = _core()
        if core is not None and self._h >= 0:
            buf = (ctypes.c_int * 32)()
            core.arc3_stats(self._h, buf)
            self.final_stats = dict(zip(self.STAT_NAMES, list(buf)))
            core.arc3_free(self._h)
            self._h = -1
        super().cleanup(*args, **kwargs)


class _PyPolicy:
    """Minimal fallback used only when the C++ core cannot be built.

    Deliberately simple: cycle the simple actions, and aim complex actions at
    object centroids rather than random pixels. Still far better than random,
    but the real policy is the C++ one.
    """

    def __init__(self, actions: list[int]) -> None:
        self.simple = [a for a in actions if 1 <= a <= 5]
        self.has6 = 6 in actions
        self.i = 0
        self.clicked: set[tuple[int, int]] = set()

    def step(self, grid, levels_completed: int):
        self.i += 1
        if self.simple and (not self.has6 or self.i % 3):
            return self.simple[self.i % len(self.simple)], 0, 0
        if self.has6:
            for y in range(2, 64, 4):
                for x in range(2, 64, 4):
                    if (x, y) not in self.clicked:
                        self.clicked.add((x, y))
                        return 6, x, y
        return (self.simple[self.i % len(self.simple)] if self.simple else 1), 0, 0
